### ISSUE TITLE
Mismatch between documentation and API responses

### ISSUE THREAD

**Issue by Tearth** [shahar603/Launch-Dashboard-API#22]
There is a small mismatch between what the documentation says, and what API returns from the endpoints: "[analysed](https://github.com/shahar603/Launch-Dashboard-API/wiki/Analysed)", "[events](https://github.com/shahar603/Launch-Dashboard-API/wiki/Events)", "[raw](https://github.com/shahar603/Launch-Dashboard-API/wiki/Raw)". We can read that all of them have mission header (with fields: "mission_id", "name", "flight_number", "launch_libray_id") like this:
```json
{
  "mission_id": "amos-17",
  "name": "Amos-17",
  "flight_number": 83,
  "launch_library_id": 1388,
  "events": [
    { "key": "maxq", "time": 66 },
    { "key": "throttle_down_start", "time": 45 }
  ]
}
```
But looks like API returns data without header, and contains only array with requested data:
```json
[
   { "key":"maxq", "time":66 },
   { "key":"throttle_down_start", "time":45 }
]
```
The only endpoint which contains mission header is "[launches](https://github.com/shahar603/Launch-Dashboard-API/wiki/Launches)", and here documentation is correct.

**Comment by shahar603** [comment]
I have updated the doc to fix the dependency. Although I do want to get your approval that the documentation is correct before I close this issue.

**Comment by Tearth** [comment]
Small things: 
 - in "raw" endpoint: API returns an array of stage/telemetry items instead of an object with raw field, eg.
```
[
    {
      "stage": 2,
      "telemetry": [
        { "time": 0, "velocity": 0.277, "altitude": 0 },
        { "time": 0.033, "velocity": 0.555, "altitude": 0 },
        ...
        { "time": 1918.333, "velocity": 9518.333, "altitude": 525},
        { "time": 1918.366, "velocity": 9518.333, "altitude": 525}
      ]
    }
]
```
 - in "analysed" endpoint: API returns array of stage/telemetry items instead of an object with array inside, eg.
```
[
   {
     "stage": 2,
     "telemetry": [
       { "time": 0, "velocity": 0.277, "altitude": 0, "velocity_y": -0.219, "velocity_x": 0.168, "acceleration": 10.698 "downrange_distance": 0, "angle": 90, "q": 0.046996480116054146 },
       { "time": 1, "velocity": 1.97, "altitude": 0.001, "velocity_y": 2.039, "velocity_x": -0.038, "acceleration": 11.285, "downrange_distance": 0, "angle": 90, "q": 2.3762015600538513 },
       ...
       { "time": 506, "velocity": 7424.372, "altitude": 163.85, "velocity_y": -32.707, "velocity_x": 7424.301, "acceleration": -0.016, "downrange_distance": 1585.22, "angle": -0.252, "q": 0 }
     ]
   }
]
```
 - in "events" endpoint: API returns array of events instead of an object with "events" field and array inside, eg.
```
[
    { "key": "maxq", "time": 66 },
    { "key": "throttle_down_start", "time": 45 },
    { "key": "throttle_down_end", "time": 91 },
    { "key": "meco", "time": 169 },
    ...
]
```

**Comment by shahar603** [comment]
Fixed that as well now

**Comment by Tearth** [comment]
Looks good now, thanks
