### ISSUE TITLE
WebSocket - connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by Tearth** [shahar603/Launch-Dashboard-API#23]
I was trying to connect to the WebSocket server (wss://api.launchdashboard.space/), but looks like there is some problem. I ran the sample code in Node.js with success, but it's the only one which works - I tried a few libraries in C#, online WebSocket clients and they can't connect.

You can check it here for example: http://demos.kaazing.com/echo/index.html. When trying to connect, the log shows these messages:
```
CONNECT: wss://api.launchdashboard.space/
CLOSED: (1006) 
```
Looking at the developer console in Chrome we get some additional info:
```
WebSocket connection to 'wss://api.launchdashboard.space/?.kl=Y' failed: Connection closed before receiving a handshake response
```
I don't know Node.js too well to check code in your backend, but I've searched in Google and looks like it's quite common problem with Socket.io library, especially when someone creates by accident two instances of it on example. Sample links:

GitHub issues -
https://github.com/socketio/socket.io/issues/2045
https://github.com/feathersjs-ecosystem/socketio/issues/84

StackOverflow -
https://stackoverflow.com/questions/26665840/socket-io-failed-connection-closed-before-receiving-a-handshake-response/44196108

**Comment by shahar603** [comment]
Thanks for raising this issue. I'm looking into it.

**Comment by shahar603** [comment]
I'm having difficulties finding the bug. I'm pretty sure I'm not creating two instances as you can see in the code: https://github.com/shahar603/Launch-Dashboard-API/blob/master/src/app.js#L158 .

I'm really not sure what the problem is. Do you have any idea? @Tearth

**Comment by Tearth** [comment]
I will try to take a look at this and let you know if I find something

**Comment by Tearth** [comment]
Ok, so I've done a small investigation and it looks like I finally know where is the problem. socket.io doesn't use "pure" WebSocket protocol - which implicates that typical WebSocket client in C# or any other language is not compatible with the server and won't communicate properly. I didn't know about this fact earlier (as I said earlier, I don't know npm environment well) but this explain why your example Node.js client (using socket.io-client) works well. Sadly it looks like there is not too many libraries for C# which would support socket.io server, but it's something I will check more later.

To confirm this, I've run some example code using "pure" WebSocket server - and as expected, C# client started working without any troubles.
```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 });

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });

  ws.send('something');
});
```
So summarizing, it's not something you can actually repair (maybe except writing explicitly in wiki that pure WebSocket clients may not work). I will try to look at more ways to support socket.io in C#, or consider writing own library.

**Comment by Tearth** [comment]
On the other side, I found that connecting to the `wss://api.launchdashboard.space/socket.io/?EIO=3&transport=websocket` and sending `42/join,["raw","analysed"]` ends with success using standard WebSocket client. I will test it during the upcoming launch.

**Comment by shahar603** [comment]
Nice job! I'll update the documentation to match your finding. I might update the code in the future to comply with "pure" websockets.
