### ISSUE TITLE
Please contact us

### ISSUE THREAD

**Issue by n8ores** [shahar603/Launch-Dashboard-API#25]
Dear Sharhar603,

I have been looking closely at your live telemetry feed and the Telemetry API/WebSockets and I am very interested in trying this capability into our core software at Saber Astronautics. 

Is there a good email address I can get in touch with you at? Alternatively, feel free to send me an email to: nathan.parrott@saberastro.com

Regards,

**Comment by shahar603** [comment]
No problem.
Send an email to: shahar@launchdashboard.space
