### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by mdichter** [shahar603/Launch-Dashboard-API#35]
Hi Shahar. The server at api.launchdashboard.space has been down for the last few days. I was hoping to take a look at some more recent launch data.

**Comment by shahar603** [comment]
Thanks for letting me know. I am taking a look at this issue right now.

**Comment by pulkitpahuja** [comment]
Server is down right now too ..

**Comment by shahar603** [comment]
Server is back up

**Comment by shahar603** [comment]
Issue has been resolved
